- color: fef2c0
  description: Author 可申请锁住当前讨论
  name: Locked
- color: ff008a
  description: ""
  name: ARM
- color: 5A7584
  description: ""
  name: x86
- color: 9FD14A
  description: ""
  name: 嵌入式
- color: e6c74a
  description: ""
  name: Arduino
- color: DF6248
  description: ""
  name: 树莓派
- color: 123B15
  description: ""
  name: 路由器
- color: 306FB2
  description: ""
  name: NAS
- color: 0052CC
  description: ""
  name: 交换机
- color: 0CE712
  description: ""
  name: GPU
- color: AE185D
  description: ""
  name: DPU
- color: EEAEB4
  description: ""
  name: 智能家居
